### PR TITLE
fix incorrect regex for netherlands

### PR DESCRIPTION
**Pull request by tiptop96**

### CODE REVIEW

**Comment by tiptop96** [comment]
Can't seem to find anywhere that indicates that there could be 3 numbers at the end.

**Comment by JanmanX** [comment]
Hi @tiptop96 !

Thanks for the pull request, we appreciate it!

I looked over it, and the code looks fine, but I cannot find any evidence that the Netherlands tax numbers can have 3 numbers at the end?
https://www.avalara.com/vatlive/en/eu-vat-rules/eu-vat-number-registration/eu-vat-number-formats.html
https://en.wikipedia.org/wiki/VAT_identification_number

**Comment by tiptop96** [comment]
Hey @JanmanX I might be missundertstanding you but I think that is the exact thing this PR sorts out?

**Comment by JanmanX** [comment]
@tiptop96 Sorry, my bad, I read the PR wrong.

Thanks!

**Pull request merged**
